@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Luis",
    "email": "luis.senarode2@gmail.com",
    "password": "123456"
}

###


# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "luis.senarode2@gmail.com",
  "password": "123456"
}

###

# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Category 1",
  "type": "income",
  "estimatedAmount": 1000
}

###

# @name create_transaction
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Transaction 1",
  "amount": 500,
  "date": "2012-04-23T18:25:43.511Z",
  "categoryId": "2dbd367e-5600-42a6-bd96-c4f2484cb7df"
}

###

# @name list_transactions
GET {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###


# @name list_categories_stats
GET {{baseUrl}}/categories-stats
Content-Type: application/json
Authorization: Bearer {{authToken}}

###